# This is a basic workflow to help you get started with Actions

name: GitHub Actions Zero
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-github-actions-env:
    runs-on: ubuntu-latest
    
    steps:
      - name: Show Trigger Event
      run: echo "This job was triggered by a ${{ github.event_name }} event."

  
